server {
    listen 80;
    
    # Nén Gzip tốc độ cao
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        # Định tuyến SPA (Single Page Application) - Cho phép React Router hoạt động khi refresh page (F5)
        try_files $uri $uri/ /index.html;
    }

    # Bỏ qua kiểm tra file ẩn / rác
    location ~ /\.ht {
        deny  all;
    }
}
